### ISSUE TITLE
sketch window isnt displaying after I input the parameter P3D to the size() function. (Processing)

### ISSUE THREAD

**Issue by rydzign** [processing/processing-examples#16]
Just trying to display the beginning sketch for the code to draw in 3D. The window doesnt pop up for the P3D parameter, i'm wondering if I'm doing this wrong.

void setup() {
  size(600,600,P3D); //P3D isn't working
  background(255);
}

void draw() {
stroke(255);
noFill();
box(40);
}

//trying to display a simple 3D shape. Then eventually alter a 3D camera to my liking. I  haven't added any camera code yet as you can tell. Haven't gotten that far.

//With the parameter P3D
<img width="1792" alt="Screenshot 2022-12-03 at 5 12 12 PM" src="https://user-images.githubusercontent.com/32995842/205469218-40a08e4b-9b71-4fb7-b7e1-06474ec1770c.png">

//Without the parameter P3D
<img width="1792" alt="Screenshot 2022-12-03 at 5 12 01 PM" src="https://user-images.githubusercontent.com/32995842/205469222-3984d15c-4ed9-4af5-928a-b2dcc2eb494a.png">

**Comment by SableRaf** [comment]
Hi @rydzign. I'm assuming that you are running macOS Ventura. This issue (https://github.com/processing/processing4/issues/544) was fixed with Processing's 4.0.2 release. Please [download the latest version](https://processing.org/download) on the Processing website.

**Comment by SableRaf** [comment]
Hello @xlinx 

Are you saying that you are trying to use the `initSingleton` method from the `com.jogamp.opengl.GLProfile` class with Processing on macOS Ventura, but it is not working for you? You mention that you have installed Processing 4.1.1 and JDK 17.0.4, and that you had the same issue when you were using Processing 3 and JDK 1.8.0.292. Is that correct? Please let me know if I have understood your message correctly.

Is your problem similar to the issue above? (_"sketch window isnt displaying after I input the parameter P3D to the size() function"_) If not you may want to [open a new issue](https://github.com/processing/processing4/issues/new) or ask your question on the [Processing Forum](https://discourse.processing.org/).

**Comment by xlinx** [comment]
@SableRaf  sorry for the delay, becoz some healthy issue.
I mean on macOS 13, I have some old projects, processing4 work fine with com.jogamp.opengl.GLProfile.initSingleton();
but the processing3 project with that method of calling still not working. 

Those old projects can not trans from p3 to p4, that bcoz I use p3 as lib on IntelliJ which is a huge project, and it's running on others OLD Mac mini that cant update the system. But my develop macbook pro is running new OS13...

So I still need to develop p3(JDK1.8) with the new OS13 . Does anyone find a solution to this?

**Comment by SableRaf** [comment]
Hello @xlinx, it looks like your issue may not be related to the topic being discussed here. To help keep this repository organized, this conversation will be locked. If you have any other questions or concerns, I would suggest reaching out to the appropriate repository or posting on the [Processing forum](https://discourse.processing.org/). The community there will be happy to help. Thank you.
